// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"
	structures "project/structures"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ServiceTodo is an autogenerated mock type for the ServiceTodo type
type ServiceTodo struct {
	mock.Mock
}

type ServiceTodo_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceTodo) EXPECT() *ServiceTodo_Expecter {
	return &ServiceTodo_Expecter{mock: &_m.Mock}
}

// AssignUserToTodo provides a mock function with given fields: ctx, todoId, listId, username
func (_m *ServiceTodo) AssignUserToTodo(ctx context.Context, todoId uuid.UUID, listId uuid.UUID, username string) error {
	ret := _m.Called(ctx, todoId, listId, username)

	if len(ret) == 0 {
		panic("no return value specified for AssignUserToTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, todoId, listId, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceTodo_AssignUserToTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignUserToTodo'
type ServiceTodo_AssignUserToTodo_Call struct {
	*mock.Call
}

// AssignUserToTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todoId uuid.UUID
//   - listId uuid.UUID
//   - username string
func (_e *ServiceTodo_Expecter) AssignUserToTodo(ctx interface{}, todoId interface{}, listId interface{}, username interface{}) *ServiceTodo_AssignUserToTodo_Call {
	return &ServiceTodo_AssignUserToTodo_Call{Call: _e.mock.On("AssignUserToTodo", ctx, todoId, listId, username)}
}

func (_c *ServiceTodo_AssignUserToTodo_Call) Run(run func(ctx context.Context, todoId uuid.UUID, listId uuid.UUID, username string)) *ServiceTodo_AssignUserToTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *ServiceTodo_AssignUserToTodo_Call) Return(_a0 error) *ServiceTodo_AssignUserToTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceTodo_AssignUserToTodo_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *ServiceTodo_AssignUserToTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeTodoStatus provides a mock function with given fields: ctx, todoId, listId
func (_m *ServiceTodo) ChangeTodoStatus(ctx context.Context, todoId uuid.UUID, listId uuid.UUID) error {
	ret := _m.Called(ctx, todoId, listId)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTodoStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, todoId, listId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceTodo_ChangeTodoStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeTodoStatus'
type ServiceTodo_ChangeTodoStatus_Call struct {
	*mock.Call
}

// ChangeTodoStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - todoId uuid.UUID
//   - listId uuid.UUID
func (_e *ServiceTodo_Expecter) ChangeTodoStatus(ctx interface{}, todoId interface{}, listId interface{}) *ServiceTodo_ChangeTodoStatus_Call {
	return &ServiceTodo_ChangeTodoStatus_Call{Call: _e.mock.On("ChangeTodoStatus", ctx, todoId, listId)}
}

func (_c *ServiceTodo_ChangeTodoStatus_Call) Run(run func(ctx context.Context, todoId uuid.UUID, listId uuid.UUID)) *ServiceTodo_ChangeTodoStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ServiceTodo_ChangeTodoStatus_Call) Return(_a0 error) *ServiceTodo_ChangeTodoStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceTodo_ChangeTodoStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ServiceTodo_ChangeTodoStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CheckIfListContainsTodo provides a mock function with given fields: ctx, todoId, listId
func (_m *ServiceTodo) CheckIfListContainsTodo(ctx context.Context, todoId uuid.UUID, listId uuid.UUID) bool {
	ret := _m.Called(ctx, todoId, listId)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfListContainsTodo")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, todoId, listId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ServiceTodo_CheckIfListContainsTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIfListContainsTodo'
type ServiceTodo_CheckIfListContainsTodo_Call struct {
	*mock.Call
}

// CheckIfListContainsTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todoId uuid.UUID
//   - listId uuid.UUID
func (_e *ServiceTodo_Expecter) CheckIfListContainsTodo(ctx interface{}, todoId interface{}, listId interface{}) *ServiceTodo_CheckIfListContainsTodo_Call {
	return &ServiceTodo_CheckIfListContainsTodo_Call{Call: _e.mock.On("CheckIfListContainsTodo", ctx, todoId, listId)}
}

func (_c *ServiceTodo_CheckIfListContainsTodo_Call) Run(run func(ctx context.Context, todoId uuid.UUID, listId uuid.UUID)) *ServiceTodo_CheckIfListContainsTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ServiceTodo_CheckIfListContainsTodo_Call) Return(_a0 bool) *ServiceTodo_CheckIfListContainsTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceTodo_CheckIfListContainsTodo_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) bool) *ServiceTodo_CheckIfListContainsTodo_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTodo provides a mock function with given fields: ctx, todoInput, listId
func (_m *ServiceTodo) CreateTodo(ctx context.Context, todoInput structures.TodoInput, listId uuid.UUID) (*structures.TodoOutput, error) {
	ret := _m.Called(ctx, todoInput, listId)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *structures.TodoOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, structures.TodoInput, uuid.UUID) (*structures.TodoOutput, error)); ok {
		return rf(ctx, todoInput, listId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, structures.TodoInput, uuid.UUID) *structures.TodoOutput); ok {
		r0 = rf(ctx, todoInput, listId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*structures.TodoOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, structures.TodoInput, uuid.UUID) error); ok {
		r1 = rf(ctx, todoInput, listId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceTodo_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type ServiceTodo_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todoInput structures.TodoInput
//   - listId uuid.UUID
func (_e *ServiceTodo_Expecter) CreateTodo(ctx interface{}, todoInput interface{}, listId interface{}) *ServiceTodo_CreateTodo_Call {
	return &ServiceTodo_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, todoInput, listId)}
}

func (_c *ServiceTodo_CreateTodo_Call) Run(run func(ctx context.Context, todoInput structures.TodoInput, listId uuid.UUID)) *ServiceTodo_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(structures.TodoInput), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ServiceTodo_CreateTodo_Call) Return(_a0 *structures.TodoOutput, _a1 error) *ServiceTodo_CreateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceTodo_CreateTodo_Call) RunAndReturn(run func(context.Context, structures.TodoInput, uuid.UUID) (*structures.TodoOutput, error)) *ServiceTodo_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function with given fields: ctx, todoId, listId
func (_m *ServiceTodo) DeleteTodo(ctx context.Context, todoId uuid.UUID, listId uuid.UUID) (*structures.TodoOutput, error) {
	ret := _m.Called(ctx, todoId, listId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 *structures.TodoOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*structures.TodoOutput, error)); ok {
		return rf(ctx, todoId, listId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *structures.TodoOutput); ok {
		r0 = rf(ctx, todoId, listId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*structures.TodoOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, todoId, listId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceTodo_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type ServiceTodo_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todoId uuid.UUID
//   - listId uuid.UUID
func (_e *ServiceTodo_Expecter) DeleteTodo(ctx interface{}, todoId interface{}, listId interface{}) *ServiceTodo_DeleteTodo_Call {
	return &ServiceTodo_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, todoId, listId)}
}

func (_c *ServiceTodo_DeleteTodo_Call) Run(run func(ctx context.Context, todoId uuid.UUID, listId uuid.UUID)) *ServiceTodo_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ServiceTodo_DeleteTodo_Call) Return(_a0 *structures.TodoOutput, _a1 error) *ServiceTodo_DeleteTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceTodo_DeleteTodo_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*structures.TodoOutput, error)) *ServiceTodo_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTasks provides a mock function with given fields: ctx, listId
func (_m *ServiceTodo) GetAllTasks(ctx context.Context, listId uuid.UUID) []structures.TodoOutput {
	ret := _m.Called(ctx, listId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []structures.TodoOutput
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []structures.TodoOutput); ok {
		r0 = rf(ctx, listId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]structures.TodoOutput)
		}
	}

	return r0
}

// ServiceTodo_GetAllTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTasks'
type ServiceTodo_GetAllTasks_Call struct {
	*mock.Call
}

// GetAllTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - listId uuid.UUID
func (_e *ServiceTodo_Expecter) GetAllTasks(ctx interface{}, listId interface{}) *ServiceTodo_GetAllTasks_Call {
	return &ServiceTodo_GetAllTasks_Call{Call: _e.mock.On("GetAllTasks", ctx, listId)}
}

func (_c *ServiceTodo_GetAllTasks_Call) Run(run func(ctx context.Context, listId uuid.UUID)) *ServiceTodo_GetAllTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ServiceTodo_GetAllTasks_Call) Return(_a0 []structures.TodoOutput) *ServiceTodo_GetAllTasks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceTodo_GetAllTasks_Call) RunAndReturn(run func(context.Context, uuid.UUID) []structures.TodoOutput) *ServiceTodo_GetAllTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function with given fields: ctx, todoId, listId
func (_m *ServiceTodo) GetTodo(ctx context.Context, todoId uuid.UUID, listId uuid.UUID) (*structures.TodoOutput, error) {
	ret := _m.Called(ctx, todoId, listId)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 *structures.TodoOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*structures.TodoOutput, error)); ok {
		return rf(ctx, todoId, listId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *structures.TodoOutput); ok {
		r0 = rf(ctx, todoId, listId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*structures.TodoOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, todoId, listId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceTodo_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type ServiceTodo_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todoId uuid.UUID
//   - listId uuid.UUID
func (_e *ServiceTodo_Expecter) GetTodo(ctx interface{}, todoId interface{}, listId interface{}) *ServiceTodo_GetTodo_Call {
	return &ServiceTodo_GetTodo_Call{Call: _e.mock.On("GetTodo", ctx, todoId, listId)}
}

func (_c *ServiceTodo_GetTodo_Call) Run(run func(ctx context.Context, todoId uuid.UUID, listId uuid.UUID)) *ServiceTodo_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ServiceTodo_GetTodo_Call) Return(_a0 *structures.TodoOutput, _a1 error) *ServiceTodo_GetTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceTodo_GetTodo_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*structures.TodoOutput, error)) *ServiceTodo_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodoAssignee provides a mock function with given fields: ctx, todoId
func (_m *ServiceTodo) GetTodoAssignee(ctx context.Context, todoId uuid.UUID) string {
	ret := _m.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for GetTodoAssignee")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, todoId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ServiceTodo_GetTodoAssignee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodoAssignee'
type ServiceTodo_GetTodoAssignee_Call struct {
	*mock.Call
}

// GetTodoAssignee is a helper method to define mock.On call
//   - ctx context.Context
//   - todoId uuid.UUID
func (_e *ServiceTodo_Expecter) GetTodoAssignee(ctx interface{}, todoId interface{}) *ServiceTodo_GetTodoAssignee_Call {
	return &ServiceTodo_GetTodoAssignee_Call{Call: _e.mock.On("GetTodoAssignee", ctx, todoId)}
}

func (_c *ServiceTodo_GetTodoAssignee_Call) Run(run func(ctx context.Context, todoId uuid.UUID)) *ServiceTodo_GetTodoAssignee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ServiceTodo_GetTodoAssignee_Call) Return(_a0 string) *ServiceTodo_GetTodoAssignee_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceTodo_GetTodoAssignee_Call) RunAndReturn(run func(context.Context, uuid.UUID) string) *ServiceTodo_GetTodoAssignee_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function with given fields: ctx, todoId, listId, todoUpdate
func (_m *ServiceTodo) UpdateTodo(ctx context.Context, todoId uuid.UUID, listId uuid.UUID, todoUpdate structures.TodoInput) (*structures.TodoOutput, error) {
	ret := _m.Called(ctx, todoId, listId, todoUpdate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *structures.TodoOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, structures.TodoInput) (*structures.TodoOutput, error)); ok {
		return rf(ctx, todoId, listId, todoUpdate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, structures.TodoInput) *structures.TodoOutput); ok {
		r0 = rf(ctx, todoId, listId, todoUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*structures.TodoOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, structures.TodoInput) error); ok {
		r1 = rf(ctx, todoId, listId, todoUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceTodo_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type ServiceTodo_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todoId uuid.UUID
//   - listId uuid.UUID
//   - todoUpdate structures.TodoInput
func (_e *ServiceTodo_Expecter) UpdateTodo(ctx interface{}, todoId interface{}, listId interface{}, todoUpdate interface{}) *ServiceTodo_UpdateTodo_Call {
	return &ServiceTodo_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, todoId, listId, todoUpdate)}
}

func (_c *ServiceTodo_UpdateTodo_Call) Run(run func(ctx context.Context, todoId uuid.UUID, listId uuid.UUID, todoUpdate structures.TodoInput)) *ServiceTodo_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(structures.TodoInput))
	})
	return _c
}

func (_c *ServiceTodo_UpdateTodo_Call) Return(_a0 *structures.TodoOutput, _a1 error) *ServiceTodo_UpdateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceTodo_UpdateTodo_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, structures.TodoInput) (*structures.TodoOutput, error)) *ServiceTodo_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceTodo creates a new instance of ServiceTodo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceTodo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceTodo {
	mock := &ServiceTodo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
