BEGIN;

DROP TABLE IF EXISTS list CASCADE;

DROP TABLE IF EXISTS users_lists CASCADE;

DROP TABLE IF EXISTS todo CASCADE;

DROP TYPE IF EXISTS priority_type CASCADE;

DROP TYPE IF EXISTS status_type CASCADE;

DROP FUNCTION IF EXISTS modify_time_field();

COMMIT;